-- Total patients
SELECT COUNT(*) AS TOTAL_PATIENTS
FROM er.ER_Visits;

-- Average wait time
SELECT ROUND(AVG(PATIENT_WAITTIME),1) AS AVG_WAIT_TIME
FROM er.ER_Visits;

-- Average satisfaction score (excluding 0)
SELECT ROUND(AVG(
    CASE WHEN PATIENT_SATISFACTION_SCORE > 0 
    THEN PATIENT_SATISFACTION_SCORE END),2) AS AVG_SATISFACTION
FROM er.ER_Visits;

-- Admission rate %
SELECT ROUND(AVG(PATIENT_ADMISSION_FLAG_NUMERIC) * 100,1) AS ADMISSION_RATE_PCT
FROM er.ER_Visits;
