-- Gender distribution
SELECT PATIENT_GENDER, COUNT(*) AS TOTAL_PATIENTS
FROM er.ER_Visits
GROUP BY PATIENT_GENDER
ORDER BY TOTAL_PATIENTS DESC;

-- Age group distribution
SELECT AGE_GROUP, COUNT(*) AS TOTAL_PATIENTS
FROM er.ER_Visits
GROUP BY AGE_GROUP
ORDER BY TOTAL_PATIENTS DESC;

-- Race distribution
SELECT PATIENT_RACE, COUNT(*) AS TOTAL_PATIENTS
FROM er.ER_Visits
GROUP BY PATIENT_RACE
ORDER BY TOTAL_PATIENTS DESC;

-- Satisfaction by age group
SELECT AGE_GROUP,
       ROUND(AVG(PATIENT_SATISFACTION_SCORE),2) AS AVG_SATISFACTION
FROM er.ER_Visits
WHERE PATIENT_SATISFACTION_SCORE > 0
GROUP BY AGE_GROUP;
