-- Referral distribution
SELECT DEPARTMENT_REFERRAL,
       COUNT(*) AS VISITS
FROM er.ER_Visits
GROUP BY DEPARTMENT_REFERRAL
ORDER BY VISITS DESC;

-- Wait time by referral
SELECT DEPARTMENT_REFERRAL,
       ROUND(AVG(PATIENT_WAITTIME),1) AS AVG_WAIT_TIME
FROM er.ER_Visits
GROUP BY DEPARTMENT_REFERRAL;

-- Admission rate by referral
SELECT DEPARTMENT_REFERRAL,
       ROUND(AVG(PATIENT_ADMISSION_FLAG_NUMERIC)*100,1) AS ADMISSION_RATE_PCT
FROM er.ER_Visits
GROUP BY DEPARTMENT_REFERRAL;
