-- View 1: KPI Summary
CREATE VIEW vw_er_kpis AS
SELECT 
    COUNT(*) AS TOTAL_PATIENTS,
    ROUND(AVG(PATIENT_WAITTIME),1) AS AVG_PATIENT_WAITTIME,
    ROUND(AVG(CASE WHEN PATIENT_SATISFACTION_SCORE > 0 
        THEN PATIENT_SATISFACTION_SCORE END),2) AS AVG_PATIENT_SATISFACTION_SCORE,
    ROUND(AVG(PATIENT_ADMISSION_FLAG_NUMERIC)*100,1) AS ADMISSION_RATE_PCT
FROM er.ER_Visits;

--------------------------------------------------

-- View 2: Hourly Heatmap
CREATE VIEW vw_hourly_volume AS
SELECT
    DAY_OF_WEEK AS DAY_OF_WEEK_NAME,
    CASE 
        WHEN DAY_OF_WEEK = 'Monday' THEN 1
        WHEN DAY_OF_WEEK = 'Tuesday' THEN 2
        WHEN DAY_OF_WEEK = 'Wednesday' THEN 3
        WHEN DAY_OF_WEEK = 'Thursday' THEN 4
        WHEN DAY_OF_WEEK = 'Friday' THEN 5
        WHEN DAY_OF_WEEK = 'Saturday' THEN 6
        WHEN DAY_OF_WEEK = 'Sunday' THEN 7
    END AS DAY_OF_WEEK_NUM,
    HOUR_OF_ARRIVAL,
    COUNT(*) AS VISITS,
    ROUND(AVG(PATIENT_WAITTIME),1) AS AVG_WAIT_TIME
FROM er.ER_Visits
GROUP BY HOUR_OF_ARRIVAL, DAY_OF_WEEK;

--------------------------------------------------

-- View 3: Department Referral
CREATE VIEW vw_dept_referral AS
SELECT 
    DEPARTMENT_REFERRAL,
    COUNT(*) AS VISITS,
    ROUND(AVG(PATIENT_WAITTIME),1) AS AVG_WAIT_TIME,
    ROUND(AVG(PATIENT_ADMISSION_FLAG_NUMERIC)*100,1) AS ADMISSION_RATE_PCT,
    ROUND(AVG(CASE WHEN PATIENT_SATISFACTION_SCORE > 0 
        THEN PATIENT_SATISFACTION_SCORE END),1) AS AVG_SATISFACTION
FROM er.ER_Visits
GROUP BY DEPARTMENT_REFERRAL;

--------------------------------------------------

-- View 4: Monthly Trends
CREATE VIEW vw_monthly_trends AS
SELECT
    FORMAT(PATIENT_ADMISSION_DATE, 'yyyy-MM') AS MONTH,
    COUNT(*) AS VISITS,
    ROUND(AVG(PATIENT_WAITTIME),1) AS AVG_WAIT_TIME,
    ROUND(AVG(CASE WHEN PATIENT_SATISFACTION_SCORE > 0 
        THEN PATIENT_SATISFACTION_SCORE END),1) AS AVG_SATISFACTION
FROM er.ER_Visits
GROUP BY FORMAT(PATIENT_ADMISSION_DATE, 'yyyy-MM');
